# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: ru

pipeline:

# See https://rasa.com/docs/rasa/tuning-your-model for more information.

  - name: SpacyNLP
    model: ru_core_news_md
    case_sensitive: False
  - name: SpacyTokenizer
  - name: RegexFeaturizer
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "Geotrend/bert-base-en-ru-cased"
    cache_dir: null
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    random_seed: 1
    constrain_similarities: True
    epochs: 150
    batch_size: [64, 256]
    num_transformer_layers: 4
    transformer_size: 256
    embedding_dimension: 30
    weight_sparsity: 0.5
    hidden_layer_sizes:
      text: [ 512, 128 ]
    entity_recognition: True
    use_masked_language_model: False
  - name: ResponseSelector
    random_seed: 1
    epochs: 150
    constrain_similarities: True
  - name: FallbackClassifier
    threshold: 0.999
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:

   - name: RulePolicy
