recipe: default.v1
language: ru

pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    use_masked_language_model: True
    constrain_similarities: True
    random_seed: 42
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.7

policies:
  - name: TEDPolicy
    constrain_similarities: True
    random_seed: 42
    max_history: 10
    epochs: 100
  - name: RulePolicy