# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: ru

pipeline:
# See https://rasa.com/docs/rasa/tuning-your-model for more information.

  - name: SpacyNLP
    model: ru_core_news_md
    case_sensitive: False
  - name: SpacyTokenizer
    intent_tokenization_flag: True
    intent_split_symbol: "+"
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
#  - name: CountVectorsFeaturizer
#  - name: CountVectorsFeaturizer
#    analyzer: "char_wb"
#    min_ngram: 1
#    max_ngram: 4
  - name: CountVectorsFeaturizer
    analyzer: "word"
    min_ngram: 1
    max_ngram: 2
  - name: LexicalSyntacticFeaturizer
    "features": [
      ['pos']
    ]
  - name: DIETClassifier
    random_seed: 1
    constrain_similarities: True
    epochs: 200
    entity_recognition: True
    use_masked_language_model: False
  - name: ResponseSelector
    random_seed: 1
    epochs: 200
    constrain_similarities: True
#  - name: DucklingEntityExtractor
#    url: "http://localhost:8000"
#    dimensions: [ "duration", "distance", "ordinal" ]
#    locale: "ru_RU"
  - name: DucklingEntityExtractor
    url: "http://localhost:8000"
    dimensions: [ "temperature", "number" ]
    locale: "en_EN"
  - name: FallbackClassifier
    threshold: 0.8
    ambiguity_threshold: 0.1
    constrain_similarities: True

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/

policies:
  - name: RulePolicy
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 200
    constrain_similarities: True
